export const ExerciseType = {
	Rest: 'Rest Day',
	Strength: 'Strength Training',
	Cardio: 'Cardio Day',
};

export const TrainingZone = {
	WarmUp: {
		label: 'Warm Up',
	},
	BP: {
		label: 'Base Pace',
		heartRate: '125-145',
		perceivedExertion: '2-4',
	},
	MSS: {
		label: 'Maximal Steady State (MSS)',
		heartRate: '165-175',
		perceivedExertion: '5-8',
	},
	RP: {
		label: 'Race Pace (RP)',
		heartRate: '170-185',
		perceivedExertion: '7-9',
	},
	Recovery: {
		label: 'Recovery',
		heartRate: ' <125',
		perceivedExertion: '0-2',
	},
	CoolDown: {
		label: 'Cool Down',
	},
};

export const TrainingMode = {
	One: {
		id: 1,
		description: 'Horizontal or Seated training',
		examples: [
			'Recumbent bike',
			'Rowing ergometer',
			'Swimming (kicking with a kickboard)',
		],
	},
	Two: {
		id: 2,
		description: 'Upright bike',
	},
	Three: {
		id: 3,
		description: 'Upright exercise',
		examples: [
			'Elliptical (begin without arm motion)',
			'Treadmill (no incline)',
		],
	},
	Four: {
		id: 4,
		description: 'Upright training',
		examples: [
			'Add in use of arm motion on the elliptical and incline on the treadmill',
			'Jogging and stair stepping can be tried only after you have performed either elliptical with use of arms or treadmill walking on an incline and did not have an increase in symptoms. You do not ever have to jog if you do not want to.',
		],
	},
};

export const TRAINING_CALENDAR = [
	{
		month: 'Month 1',
		day: 1,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 1',
		day: 2,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 3, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 3,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 3, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 5,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 6,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 3, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 7,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 1',
		day: 8,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 1',
		day: 9,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 4, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 4, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 10,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 11,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 4, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 4, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 12,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 13,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 4, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 4, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 14,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 1',
		day: 15,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 1',
		day: 16,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 17,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 18,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 19,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 20,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 21,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 1',
		day: 22,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 1',
		day: 23,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 6, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 24,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 7, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 26,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 1',
		day: 27,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 7, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 1',
		day: 28,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 1,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 2,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 6, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 6, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 6, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 3,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 7, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 7, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 7, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 5,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 6,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 8, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 8, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 8, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 7,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 8,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 9,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 6, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 6, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 6, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 10,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 11,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 12,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 13,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 5, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 14,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 15,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 16,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 10, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 17,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 18,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 11, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 11, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 19,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 20,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 12, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 12, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 21,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 22,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 23,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 13, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 13, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 24,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 14, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 14, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 26,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 27,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 15, zone: TrainingZone.BP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 15, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 28,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 29,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 2',
		day: 30,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 20, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 31,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 32,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 24, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 33,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 2',
		day: 34,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 28, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 2',
		day: 35,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 3',
		day: 1,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 3',
		day: 2,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 3,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 5,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 6,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 7,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 3',
		day: 8,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 3',
		day: 9,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 10,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 11,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 12,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 13,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 20, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 14,
		type: ExerciseType.Cardio,
		timers: [{ duration: 40, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 3',
		day: 15,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 3',
		day: 16,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 17,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 18,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 19,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 20,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 21,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 3',
		day: 22,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 3',
		day: 23,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 24,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 25, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 3',
		day: 26,
		type: ExerciseType.Cardio,
		timers: [{ duration: 40, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 3',
		day: 27,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 3',
		day: 28,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 1,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 4',
		day: 2,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 3,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 5,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 6,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 20, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 7,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 4',
		day: 8,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 9,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 10,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 11,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 12,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 25, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 13,
		type: ExerciseType.Cardio,
		timers: [{ duration: 40, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 4',
		day: 14,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 4',
		day: 15,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 40, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 16,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 17,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 4',
		day: 18,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 30, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 19,
		type: ExerciseType.Cardio,
		timers: [{ duration: 40, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 4',
		day: 20,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 21,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 35, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 22,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 4',
		day: 23,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 24,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 35, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [{ duration: 40, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 4',
		day: 26,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 4',
		day: 27,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 4',
		day: 28,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duation: 40, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 1,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 5',
		day: 2,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 3,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 5',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 5,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 5',
		day: 6,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 7,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 5',
		day: 8,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 5',
		day: 9,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 10,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 5',
		day: 11,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 3, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		/* TO-DO: Add Strength Training */ month: 'Month 5',
		day: 12,
		type: ExerciseType.Cardio,
		timers: [{ duration: 40, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 5',
		day: 13,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 14,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 5',
		day: 15,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 5',
		day: 16,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 17,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 5',
		day: 18,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 3, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 19,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		/* TO-DO: Add Strength Training */ month: 'Month 5',
		day: 20,
		type: ExerciseType.Cardio,
		timers: [{ duration: 25, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 5',
		day: 21,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 50, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 22,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 5',
		day: 23,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 24,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 5',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 5',
		day: 26,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		/* TO-DO: Add Strength Training */ month: 'Month 5',
		day: 27,
		type: ExerciseType.Cardio,
		timers: [{ duration: 25, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 5',
		day: 28,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 6',
		day: 1,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 2,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 3,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 5,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 6,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 7,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 6',
		day: 8,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 9,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 10,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 6',
		day: 11,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 12,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 13,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 14,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 6',
		day: 15,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 16,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 17,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 35, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 18,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 19,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 6',
		day: 20,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 21,
		type: ExerciseType.Cardio,
		timers: [{ duration: 25, zone: TrainingZone.Recovery }],
	},
	{
		month: 'Month 6',
		day: 22,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 23,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 24,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 1, zone: TrainingZone.RP },
			{ duration: 1, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 6',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 26,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 6',
		day: 27,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 6',
		day: 28,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 30, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 1,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 7',
		day: 2,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 3,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 5,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 6,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 7,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 8,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 9,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 7',
		day: 10,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 11,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 12,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 13,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 14,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 7',
		day: 15,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 16,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 17,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 7',
		day: 18,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 19,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 7',
		day: 20,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 21,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 22,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 23,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 24,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 7',
		day: 26,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 7',
		day: 27,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 7',
		day: 28,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 1,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 2,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 3,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 4,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 5,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 6,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 40, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 7,
		type: ExerciseType.Rest,
	},
	{
		month: 'Month 8',
		day: 8,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 9,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 10,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 11,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 12,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 13,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 14,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 8',
		day: 15,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 16,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 8',
		day: 17,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 18,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 19,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 20,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 3, zone: TrainingZone.RP },
			{ duration: 3, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 8',
		day: 21,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 22,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 23,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 24,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 2, zone: TrainingZone.RP },
			{ duration: 2, zone: TrainingZone.Recovery },
			{ duration: 10, zone: TrainingZone.CoolDown },
			{ duration: 20, zone: TrainingZone.Recovery },
		],
	},
	{
		month: 'Month 8',
		day: 25,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 26,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 27,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 28,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 60, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 29,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 30,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.MSS },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 31,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 32,
		type: ExerciseType.Strength,
	},
	{
		month: 'Month 8',
		day: 33,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 34,
		type: ExerciseType.Cardio,
		timers: [
			{ duration: 10, zone: TrainingZone.WarmUp },
			{ duration: 45, zone: TrainingZone.BP },
			{ duration: 10, zone: TrainingZone.CoolDown },
		],
	},
	{
		month: 'Month 8',
		day: 35,
		type: ExerciseType.Rest,
	},
];
